const questionBanks = [
    // ================== ĐỀ SỐ 1 ==================
    [
        { id: "1_1", question: "Mục tiêu an toàn của dự án là không thương tích, không tai nạn và ____________ môi trường.", answer: "không gây ô nhiễm", acceptedAnswers: ["không gây ô nhiễm"] },
        { id: "1_2", question: "Tất cả nhân viên có trách nhiệm và được quyền dừng bất kỳ công việc nào nếu nhận thấy công việc đó ____________", answer: "không an toàn", acceptedAnswers: ["không an toàn"] },
        { id: "1_3", question: "Việc tập trung và tập thể dục buổi sáng được tiến hành vào lúc ____________", answer: "06:30~07:00 sáng", acceptedAnswers: ["06:30~07:00 sáng", "06:30-07:00 sáng", "6h30 đến 7h sáng"] },
        { id: "1_4", question: "Khẩu hiệu an toàn của công trường là \"An toàn là trên hết, ____________ , về nhà vui vẻ\".", answer: "làm việc an toàn", acceptedAnswers: ["làm việc an toàn"] },
        { id: "1_5", question: "Nếu không có ____________ , công nhân tuyệt đối không được làm việc.", answer: "giấy phép làm việc", acceptedAnswers: ["giấy phép làm việc"] },
        { id: "1_6", question: "Thời hạn của giấy phép làm việc là ____________ , và được ký hàng ngày.", answer: "7 ngày", acceptedAnswers: ["7 ngày", "7"] },
        { id: "1_7", question: "Buổi họp nhóm thảo luận phân tích mối nguy và nhiệm vụ an toàn được gọi là ____________", answer: "S.T.A.R.T MEETING", acceptedAnswers: ["S.T.A.R.T MEETING", "START MEETING"] },
        { id: "1_8", question: "Bất kỳ nhân viên nào bị phát hiện sử dụng rượu bia sẽ bị trục xuất khỏi công trường ____________", answer: "vô thời hạn", acceptedAnswers: ["vô thời hạn"] },
        { id: "1_9", question: "Hành vi trộm cắp, đánh nhau sẽ bị phạt, trục xuất và báo ____________", answer: "công an xử lý", acceptedAnswers: ["công an xử lý", "công an"] },
        { id: "1_10", question: "Thẻ ra vào công trường sẽ được phát sau khi bạn hoàn thành ____________ này.", answer: "khóa đào tạo", acceptedAnswers: ["khóa đào tạo"] },
        { id: "1_11", question: "Mọi người phải đảm bảo có ____________ trước khi làm việc.", answer: "sức khỏe tốt", acceptedAnswers: ["sức khỏe tốt"] },
        { id: "1_12", question: "Buổi họp nhóm S.T.A.R.T được tiến hành ngay tại ____________ của nhóm.", answer: "khu vực làm việc", acceptedAnswers: ["khu vực làm việc"] },
        { id: "1_13", question: "Trong buổi họp đầu giờ, giám sát và công nhân sẽ trao đổi 2 chiều về các ____________", answer: "mối nguy hiểm", acceptedAnswers: ["mối nguy hiểm", "mối nguy"] },
        { id: "1_14", question: "Mỗi nhóm làm việc tại công trường được chia tối đa ____________", answer: "20 người", acceptedAnswers: ["20 người", "20"] },
        { id: "1_15", question: "Nghiêm cấm hút thuốc, dùng chất kích thích, uống rượu bia và ____________ trong công trường.", answer: "cờ bạc", acceptedAnswers: ["cờ bạc"] },
        { id: "1_16", question: "Trước khi tiến hành thực hiện công việc, công nhân phải ký vào ____________", answer: "START CARD", acceptedAnswers: ["START CARD", "S.T.A.R.T CARD"] },
        { id: "1_17", question: "Chính sách dự án yêu cầu báo cáo và kịp thời điều tra sự cố để xác định nguyên nhân và có ____________ thích hợp.", answer: "hành động khắc phục", acceptedAnswers: ["hành động khắc phục"] },
        { id: "1_18", question: "Dự án cung cấp các chương trình đào tạo về Sức khỏe, An toàn, Môi trường và ____________", answer: "giám sát thường xuyên", acceptedAnswers: ["giám sát thường xuyên"] },
        { id: "1_19", question: "Người lao động phải đảm bảo luôn mang theo ____________ thời điểm.", answer: "thẻ tại mọi", acceptedAnswers: ["thẻ tại mọi"] },
        { id: "1_20", question: "Người lao động bắt buộc phải tham dự thảo luận và nói chuyện ____________", answer: "an toàn đầu giờ", acceptedAnswers: ["an toàn đầu giờ"] }
    ],

    // ================== ĐỀ SỐ 2 ==================
    [
        { id: "2_1", question: "Trang thiết bị bảo vệ cá nhân (PPE) bắt buộc khi vào công trường gồm: nón, kính, quần áo và ____________", answer: "giày bảo hộ", acceptedAnswers: ["giày bảo hộ"] },
        { id: "2_2", question: "Ngoài trang bị tối thiểu, công việc hàn cắt yêu cầu thêm ____________ , găng tay hàn.", answer: "mặt nạ hàn", acceptedAnswers: ["mặt nạ hàn"] },
        { id: "2_3", question: "Dọn dẹp vệ sinh sạch sẽ đồng nghĩa với ____________ cao.", answer: "năng suất lao động", acceptedAnswers: ["năng suất lao động"] },
        { id: "2_4", question: "Toàn bộ công nhân tiến hành vệ sinh khu vực làm việc ____________ khi kết thúc ngày làm việc.", answer: "15 phút trước", acceptedAnswers: ["15 phút trước"] },
        { id: "2_5", question: "Việc giữ lối đi lại sạch sẽ giúp thoát người nhanh nhất trong ____________", answer: "tình huống khẩn cấp", acceptedAnswers: ["tình huống khẩn cấp"] },
        { id: "2_6", question: "Nếu vệ sinh công nghiệp kém, các tai nạn chủ yếu xảy ra là ____________", answer: "trượt, vấp ngã", acceptedAnswers: ["trượt, vấp ngã", "trượt vấp ngã"] },
        { id: "2_7", question: "Đầu mẩu que hàn, xỉ hàn được phân loại vào nhóm ____________", answer: "chất thải nguy hại", acceptedAnswers: ["chất thải nguy hại"] },
        { id: "2_8", question: "Rác sinh hoạt bao gồm thức ăn thừa, vỏ hộp, túi nilon và ____________", answer: "giấy ăn", acceptedAnswers: ["giấy ăn"] },
        { id: "2_9", question: "Mọi người phải tuyệt đối tuân thủ mọi ____________ và hàng rào.", answer: "biển cảnh báo", acceptedAnswers: ["biển cảnh báo"] },
        { id: "2_10", question: "Hệ thống mã màu được phân chia theo 4 mùa: Đông, Xuân, Hạ và ____________", answer: "mùa Thu", acceptedAnswers: ["mùa Thu", "Thu"] },
        { id: "2_11", question: "Chai khí oxy, argon, CO2 không được để tự do mà phải được ____________ bằng dây xích.", answer: "chằng buộc", acceptedAnswers: ["chằng buộc"] },
        { id: "2_12", question: "Khi không sử dụng, các chai khí phải luôn ____________", answer: "được đậy nắp", acceptedAnswers: ["được đậy nắp", "đậy nắp"] },
        { id: "2_13", question: "Khi vận chuyển chai khí phải dùng xe chuyên dụng, tuyệt đối không dùng xe bò hoặc ____________", answer: "bê tay", acceptedAnswers: ["bê tay", "khiêng tay"] },
        { id: "2_14", question: "Bất kỳ dụng cụ cầm tay nào giúp công việc dễ dàng hơn đều phải sử dụng ____________", answer: "đúng đắn", acceptedAnswers: ["đúng đắn", "đúng cách"] },
        { id: "2_15", question: "Đôi bàn tay và các ngón tay của con người là bộ phận ____________", answer: "không thể thay thế", acceptedAnswers: ["không thể thay thế"] },
        { id: "2_16", question: "Thiết bị điện cầm tay phải được Ban Quản lý Dự án ____________ khi sử dụng.", answer: "kiểm tra trước", acceptedAnswers: ["kiểm tra trước"] },
        { id: "2_17", question: "Khi sửa chữa hoặc thay thế thiết bị điện cầm tay, bắt buộc phải ____________ điện.", answer: "rút ổ cắm", acceptedAnswers: ["rút ổ cắm", "rút phích cắm"] },
        { id: "2_18", question: "Thiết bị cầm tay phải đầy đủ nắp bảo vệ và ____________ nếu có.", answer: "tay cầm phụ", acceptedAnswers: ["tay cầm phụ"] },
        { id: "2_19", question: "Gỗ thải và kim loại vụn phải được ____________ rõ ràng tại khu vực tập kết.", answer: "dán nhãn", acceptedAnswers: ["dán nhãn", "phân loại"] },
        { id: "2_20", question: "Người lao động phải sử dụng ____________ cho mọi công việc để ngăn chặn chấn thương.", answer: "găng tay", acceptedAnswers: ["găng tay", "bao tay"] }
    ],

    // ================== ĐỀ SỐ 3 ==================
    [
        { id: "3_1", question: "Khi nâng vật nặng, mức độ tác động lên cột sống sẽ giảm khi vật nâng được đặt ____________", answer: "gần người", acceptedAnswers: ["gần người"] },
        { id: "3_2", question: "Nếu vật quá nặng, công nhân cần sử dụng ____________ hoặc gọi thêm người.", answer: "xe chuyên dụng", acceptedAnswers: ["xe chuyên dụng", "thiết bị hỗ trợ"] },
        { id: "3_3", question: "Khi tự nâng vật nặng, công nhân phải hạ thấp cơ thể và giữ cho ____________", answer: "lưng thẳng", acceptedAnswers: ["lưng thẳng"] },
        { id: "3_4", question: "Công việc có phát sinh nguồn nhiệt hoặc tia lửa được gọi là ____________", answer: "công việc nóng", acceptedAnswers: ["công việc nóng", "công việc sinh nhiệt"] },
        { id: "3_5", question: "Tại nơi làm việc phát sinh nhiệt, luôn phải trang bị ____________", answer: "bình chữa cháy", acceptedAnswers: ["bình chữa cháy"] },
        { id: "3_6", question: "Khoảng cách tối thiểu giữa nguồn sinh nhiệt và vật liệu bắt lửa là ____________", answer: "6 mét", acceptedAnswers: ["6 mét", "6m", "6"] },
        { id: "3_7", question: "Ba yếu tố tạo nên sự cháy bao gồm: Nhiên liệu, Nguồn nhiệt và ____________", answer: "khí Oxy", acceptedAnswers: ["khí Oxy", "Oxy", "O2"] },
        { id: "3_8", question: "Công nhân tham gia hoạt động nâng hạ, cẩu kéo bắt buộc phải ____________", answer: "được đào tạo", acceptedAnswers: ["được đào tạo"] },
        { id: "3_9", question: "Trong quá trình cẩu hàng, người lao động phải sử dụng ____________ để điều khiển vật nâng.", answer: "dây lèo", acceptedAnswers: ["dây lèo", "dây hướng dẫn"] },
        { id: "3_10", question: "Trước khi cẩu, phải thiết lập an toàn bằng cách kiểm tra ____________", answer: "điều kiện nền đất", acceptedAnswers: ["điều kiện nền đất", "nền đất"] },
        { id: "3_11", question: "Tấm kê chân của xe cẩu phải được đặt trên nền đất ____________", answer: "chắc chắn", acceptedAnswers: ["chắc chắn", "vững chắc"] },
        { id: "3_12", question: "Trong quá trình cẩu, tuyệt đối không được đứng ____________", answer: "dưới vật nâng", acceptedAnswers: ["dưới vật nâng", "dưới tải"] },
        { id: "3_13", question: "Nơi nghỉ ngơi, giải lao không được nằm trong góc khuất, không nhìn thấy của lái cẩu và ____________", answer: "lái máy", acceptedAnswers: ["lái máy", "người lái máy"] },
        { id: "3_14", question: "Nghiêm cấm công nhân ngủ trong cabin, buồng lái và nghỉ ngơi ngay tại ____________", answer: "tủ điện", acceptedAnswers: ["tủ điện"] },
        { id: "3_15", question: "Hóa chất và xúc tác yêu cầu người dùng phải đọc ____________ trước khi sử dụng.", answer: "bảng MSDS", acceptedAnswers: ["bảng MSDS", "MSDS"] },
        { id: "3_16", question: "Sau khi sử dụng hóa chất và xúc tác, khu vực làm việc phải được ____________", answer: "làm vệ sinh", acceptedAnswers: ["làm vệ sinh", "vệ sinh"] },
        { id: "3_17", question: "Khi có báo động khẩn cấp, người lao động phải dừng việc, di tản bằng cách đi bộ nhanh ra ____________", answer: "cổng chính", acceptedAnswers: ["cổng chính", "lối thoát hiểm"] },
        { id: "3_18", question: "Tại điểm tập trung, nhân viên không được rời đi cho đến khi đếm số lượng nhân viên ____________", answer: "hoàn thành", acceptedAnswers: ["hoàn thành", "xong"] },
        { id: "3_19", question: "Người ra tín hiệu (người xi nhan) phải đứng ở vị trí đảm bảo người lái cẩu ____________", answer: "nhìn thấy rõ", acceptedAnswers: ["nhìn thấy rõ"] },
        { id: "3_20", question: "Khi điều khiển bằng tay, hướng xi nhan phải vuông góc với ____________ của lái cẩu.", answer: "hướng nhìn", acceptedAnswers: ["hướng nhìn", "tầm nhìn"] }
    ],

    // ================== ĐỀ SỐ 4 ==================
    [
        { id: "4_1", question: "Làm việc ở độ cao đã được chứng minh là một trong những hoạt động ____________ trong xây dựng.", answer: "nguy hiểm nhất", acceptedAnswers: ["nguy hiểm nhất"] },
        { id: "4_2", question: "Theo thống kê, hai phần ba số trường hợp tử vong trong xây dựng có liên quan tới việc ____________", answer: "rơi ngã", acceptedAnswers: ["rơi ngã", "ngã từ trên cao"] },
        { id: "4_3", question: "Hệ thống chống té ngã chủ yếu bao gồm tay vịn, thành lan can, tấm chắn chân và ____________ tiêu chuẩn.", answer: "sàn thao tác", acceptedAnswers: ["sàn thao tác"] },
        { id: "4_4", question: "Lan can bảo vệ trên cao phải đạt khoảng cách từ ____________", answer: "1m đến 1.2m", acceptedAnswers: ["1m đến 1.2m", "1m - 1.2m", "1.0m đến 1.2m"] },
        { id: "4_5", question: "Tấm chặn chân trên giàn giáo phải có chiều cao ít nhất là ____________", answer: "10 cm", acceptedAnswers: ["10 cm", "10cm"] },
        { id: "4_6", question: "Người lao động phải mang dây an toàn toàn thân khi làm việc với độ cao từ ____________ hoặc lớn hơn.", answer: "1.8 mét", acceptedAnswers: ["1.8 mét", "1.8m", "1,8m"] },
        { id: "4_7", question: "Khi làm việc trên cao, 100% công nhân phải buộc chặt dây móc an toàn ở vị trí ____________", answer: "vững chắc", acceptedAnswers: ["vững chắc", "chắc chắn"] },
        { id: "4_8", question: "Chỗ móc dây an toàn phải có khả năng chịu được tải trọng ____________ tương đương 2.3 tấn.", answer: "5000 lbs", acceptedAnswers: ["5000 lbs", "5000lbs"] },
        { id: "4_9", question: "Không được sử dụng đường ống có vít, ống dẫn, hoặc tay vịn bằng gỗ làm ____________", answer: "điểm móc", acceptedAnswers: ["điểm móc", "điểm neo"] },
        { id: "4_10", question: "Dây cáp của móc dây an toàn phải có độ dày xấp xỉ ____________", answer: "12 mm", acceptedAnswers: ["12 mm", "12mm"] },
        { id: "4_11", question: "Không dùng dây thừng bện từ ____________ để làm dây cứu sinh.", answer: "sợi tự nhiên", acceptedAnswers: ["sợi tự nhiên"] },
        { id: "4_12", question: "Việc lắp đặt dây cứu sinh chỉ được thực hiện bởi ____________", answer: "người có chuyên môn", acceptedAnswers: ["người có chuyên môn"] },
        { id: "4_13", question: "Người dùng phải kiểm tra dây thắt an toàn ____________ sử dụng.", answer: "mỗi khi", acceptedAnswers: ["mỗi khi", "trước khi"] },
        { id: "4_14", question: "Các tia cực tím (UV) có thể làm giảm độ bền của dây bẹ an toàn từ ____________", answer: "25% đến 30%", acceptedAnswers: ["25% đến 30%", "25%-30%"] },
        { id: "4_15", question: "Không để dây an toàn tiếp xúc với nhiệt độ lớn hơn ____________ hoặc 82° C.", answer: "180 độ F", acceptedAnswers: ["180 độ F", "180 °F", "180°F"] },
        { id: "4_16", question: "Một vết cắt nhỏ 1 mm có thể làm mất từ 5% đến 39% ____________ của dây an toàn.", answer: "sức bền", acceptedAnswers: ["sức bền", "độ bền"] },
        { id: "4_17", question: "Khi thắt dây an toàn, phải đặt tâm của khóa chữ D nối giữa hai ____________", answer: "dây đai vai", acceptedAnswers: ["dây đai vai", "quai vai"] },
        { id: "4_18", question: "Dây đai ngực phải cho phép khoảng cách mở rộng ngực bằng ____________", answer: "một nắm tay", acceptedAnswers: ["một nắm tay"] },
        { id: "4_19", question: "Tất cả các thiết bị chống rơi phải được kiểm tra và đánh mã màu cứ ____________ một lần.", answer: "ba tháng", acceptedAnswers: ["ba tháng", "3 tháng"] },
        { id: "4_20", question: "Người lao động không được ném vật liệu, ____________ từ trên cao xuống.", answer: "thiết bị", acceptedAnswers: ["thiết bị", "dụng cụ"] }
    ],

    // ================== ĐỀ SỐ 5 ==================
    [
        { id: "5_1", question: "Người có trách nhiệm về giàn giáo mới được phép ____________ giàn giáo hoặc thay đổi cấu trúc.", answer: "treo thẻ", acceptedAnswers: ["treo thẻ"] },
        { id: "5_2", question: "Thang sử dụng phải nới rộng cao hơn khu vực làm việc khoảng 90 cm và tuân theo ____________ để đảm bảo độ dốc.", answer: "tỷ lệ 4:1", acceptedAnswers: ["tỷ lệ 4:1", "tiêu chuẩn 4:1", "tỷ lệ 4/1"] },
        { id: "5_3", question: "Khi trèo thang, công nhân phải đảm bảo tiếp xúc ____________ an toàn.", answer: "3 điểm", acceptedAnswers: ["3 điểm", "ba điểm"] },
        { id: "5_4", question: "Không sử dụng thang trên bề mặt trơn trượt, trừ khi có ____________ đi kèm.", answer: "tấm chống trượt", acceptedAnswers: ["tấm chống trượt"] },
        { id: "5_5", question: "Tuyệt đối không đặt thang trên bề mặt ____________ hoặc không ổn định.", answer: "lồi lõm", acceptedAnswers: ["lồi lõm", "gồ ghề"] },
        { id: "5_6", question: "Nếu thang đặt gần các thiết bị điện, thang phải được làm bằng chất liệu cách điện như gỗ hoặc ____________", answer: "sợi thủy tinh", acceptedAnswers: ["sợi thủy tinh"] },
        { id: "5_7", question: "Tuyệt đối không sử dụng điểm trên cùng hoặc ____________ của thang.", answer: "bậc cao nhất", acceptedAnswers: ["bậc cao nhất", "bậc trên cùng"] },
        { id: "5_8", question: "Các tay vịn 2 bên của thang di động phải cách nhau ít nhất ____________", answer: "30 cm", acceptedAnswers: ["30 cm", "30cm"] },
        { id: "5_9", question: "Nếu thang bị hỏng, phải đánh dấu ngay lập tức hoặc treo thẻ ____________", answer: "Không sử dụng", acceptedAnswers: ["Không sử dụng", "Cấm sử dụng"] },
        { id: "5_10", question: "Khi trèo lên hoặc xuống thang, mặt phải luôn ____________ thang.", answer: "hướng vào", acceptedAnswers: ["hướng vào", "quay vào"] },
        { id: "5_11", question: "Không mang đồ dùng hoặc tải trọng trên tay khi trèo thang vì có thể làm bạn ____________", answer: "mất cân bằng", acceptedAnswers: ["mất cân bằng", "mất thăng bằng"] },
        { id: "5_12", question: "Khi sử dụng thang để thao tác trên mặt sàn, thang phải cao hơn mặt sàn ít nhất ____________ trở lên.", answer: "1 mét", acceptedAnswers: ["1 mét", "1m", "1"] },
        { id: "5_13", question: "Các thanh thang phải được bố trí cách nhau từ ____________", answer: "25 đến 35 cm", acceptedAnswers: ["25 đến 35 cm", "25-35 cm", "25 đến 35cm"] },
        { id: "5_14", question: "Công nhân tuyệt đối không được đi 2 người trên ____________", answer: "cùng một thang", acceptedAnswers: ["cùng một thang", "một thang"] },
        { id: "5_15", question: "Ván sàn của giàn giáo phải được ____________ để hỗ trợ làm việc.", answer: "buộc chắc chắn", acceptedAnswers: ["buộc chắc chắn", "cố định chắc chắn"] },
        { id: "5_16", question: "Khi làm việc tại các khu vực cheo leo nguy hiểm, công nhân phải được trang bị ____________", answer: "dây cứu sinh", acceptedAnswers: ["dây cứu sinh"] },
        { id: "5_17", question: "Giàn giáo là nguyên nhân gây ra hàng ngàn tai nạn và hàng trăm ca ____________ mỗi năm.", answer: "tử vong", acceptedAnswers: ["tử vong"] },
        { id: "5_18", question: "Các tấm lót sàn giàn giáo bằng gỗ có kích thước chuẩn yêu cầu dày 5 cm và rộng ____________", answer: "20 cm", acceptedAnswers: ["20 cm", "20cm"] },
        { id: "5_19", question: "Các tấm ván lót sàn phải được đánh dấu bằng sơn ở ____________ , không sơn toàn bộ.", answer: "hai đầu", acceptedAnswers: ["hai đầu", "2 đầu"] },
        { id: "5_20", question: "Khoảng cách an toàn để khóa nối giàn giáo là cứ mỗi ____________ theo chiều cao.", answer: "4 mét", acceptedAnswers: ["4 mét", "4m", "4"] }
    ],

    // ================== ĐỀ SỐ 6 ==================
    [
        { id: "6_1", question: "Không gian hạn chế là nơi đủ rộng để đi vào làm việc nhưng bị hạn chế ____________ và không thiết kế làm việc lâu dài.", answer: "lối ra vào", acceptedAnswers: ["lối ra vào"] },
        { id: "6_2", question: "Các mối nguy hiểm vật lý trong không gian hạn chế bao gồm tiếng ồn, nhiệt độ, điện, và ____________", answer: "tầm nhìn hạn chế", acceptedAnswers: ["tầm nhìn hạn chế"] },
        { id: "6_3", question: "Không khí thông thường có nồng độ oxy là ____________", answer: "khoảng 21%", acceptedAnswers: ["khoảng 21%", "21%"] },
        { id: "6_4", question: "Không khí bị coi là thiếu oxy khi nồng độ oxy ở mức ____________", answer: "dưới 19.5%", acceptedAnswers: ["dưới 19.5%", "dưới 19,5%"] },
        { id: "6_5", question: "Khi nồng độ oxy từ 15-19%, con người bắt đầu có triệu chứng giảm ____________", answer: "khả năng phối hợp", acceptedAnswers: ["khả năng phối hợp"] },
        { id: "6_6", question: "Môi trường có nồng độ oxy trên 23.5% được gọi là ____________", answer: "giàu oxy", acceptedAnswers: ["giàu oxy"] },
        { id: "6_7", question: "Không được tồn trữ bồn hoặc ____________ trong không gian kín.", answer: "bình khí nén", acceptedAnswers: ["bình khí nén", "chai khí nén"] },
        { id: "6_8", question: "Khí Hydro Sunphua (H2S) là khí không màu, nặng hơn không khí và có mùi ____________", answer: "trứng thối", acceptedAnswers: ["trứng thối"] },
        { id: "6_9", question: "H2S có thể làm mất khả năng khứu giác của con người ở nồng độ ____________ trở lên.", answer: "100 PPM", acceptedAnswers: ["100 PPM", "100ppm"] },
        { id: "6_10", question: "Cacbon Monoxit (CO) là sản phẩm phụ của quá trình đốt cháy, nhẹ hơn không khí và hoàn toàn ____________", answer: "không mùi", acceptedAnswers: ["không mùi"] },
        { id: "6_11", question: "Hóa chất độc hại trong không gian kín có thể đi vào cơ thể qua hô hấp, nuốt, hoặc ____________", answer: "hấp thụ qua da", acceptedAnswers: ["hấp thụ qua da", "thấm qua da"] },
        { id: "6_12", question: "Các loại khí dễ cháy thường gặp trong không gian kín bao gồm CH4, C2H2, nhiên liệu, dung môi và ____________", answer: "bụi than", acceptedAnswers: ["bụi than"] },
        { id: "6_13", question: "Sự khuếch đại âm thanh trong không gian kín tạo ra mối nguy về ____________ làm tác động khả năng giao tiếp.", answer: "tiếng ồn", acceptedAnswers: ["tiếng ồn"] },
        { id: "6_14", question: "Làm sạch không gian kín bằng ____________ là một nguyên nhân gây thiếu oxy.", answer: "khí trơ", acceptedAnswers: ["khí trơ"] },
        { id: "6_15", question: "Hóa chất kích ứng có thể làm người lao động chóng mặt, buồn nôn hoặc ____________", answer: "khó thở", acceptedAnswers: ["khó thở"] },
        { id: "6_16", question: "Không sử dụng ____________ để thông gió trong không gian hạn chế.", answer: "oxy nguyên chất", acceptedAnswers: ["oxy nguyên chất", "khi oxy nguyên chất"] },
        { id: "6_17", question: "Nồng độ giới hạn an toàn tiếp xúc cho phép của khí CO trong 8 giờ là ____________", answer: "25 PPM", acceptedAnswers: ["25 PPM", "25ppm"] },
        { id: "6_18", question: "Mối nguy ngập lụt, sụt, lún hoặc ____________ thường hiện diện trong không gian kín.", answer: "bất tỉnh", acceptedAnswers: ["bất tỉnh"] },
        { id: "6_19", question: "Các thiết bị bảo hộ lao động bổ sung có thể làm tăng nhiệt độ cơ thể do ____________ nặng nề.", answer: "trọng lượng", acceptedAnswers: ["trọng lượng", "sức nặng"] },
        { id: "6_20", question: "Người lao động làm việc trong không gian kín cần được ____________ thường xuyên hơn.", answer: "nghỉ giải lao", acceptedAnswers: ["nghỉ giải lao", "nghỉ ngơi"] }
    ],

    // ================== ĐỀ SỐ 7 ==================
    [
        { id: "7_1", question: "Khi dừng công việc, phải bố trí ____________ để cấm người không phận sự vào không gian kín.", answer: "rào chắn cứng", acceptedAnswers: ["rào chắn cứng", "rào chắn"] },
        { id: "7_2", question: "Biển cảnh báo phải được đặt ở tất cả các ____________ của không gian kín.", answer: "lối ra vào", acceptedAnswers: ["lối ra vào", "cửa ra vào"] },
        { id: "7_3", question: "Trước khi vào làm việc, người lao động phải được cấp phép, khỏe mạnh về thể chất và ____________", answer: "tinh thần", acceptedAnswers: ["tinh thần"] },
        { id: "7_4", question: "Chỉ sử dụng thiết bị điện có ____________ để thắp sáng trong không gian kín.", answer: "điện áp thấp", acceptedAnswers: ["điện áp thấp"] },
        { id: "7_5", question: "Giấy phép làm việc trong không gian hạn chế phải được yêu cầu trước ____________", answer: "24 giờ", acceptedAnswers: ["24 giờ", "24h", "24 tiếng"] },
        { id: "7_6", question: "Bản giấy phép làm việc bắt buộc phải được đặt tại ____________ không gian kín.", answer: "lối vào", acceptedAnswers: ["lối vào", "cửa vào"] },
        { id: "7_7", question: "Không gian kín phải được kiểm tra khí ____________ trước khi vào làm việc.", answer: "1 tiếng", acceptedAnswers: ["1 tiếng", "1 giờ", "1h"] },
        { id: "7_8", question: "Nếu công việc bị tạm dừng vì bất kỳ lý do gì, cần phải ____________ khí trước khi tiếp tục.", answer: "kiểm tra lại", acceptedAnswers: ["kiểm tra lại", "đo lại"] },
        { id: "7_9", question: "Người được Quyền Đo Khí (AGT) phải đo khí ở mọi khu vực trong không gian kín từ ____________", answer: "bên ngoài", acceptedAnswers: ["bên ngoài"] },
        { id: "7_10", question: "Các thiết bị điện phải kết nối qua thiết bị chống dòng rò được đặt ở ____________ không gian kín.", answer: "bên ngoài", acceptedAnswers: ["bên ngoài"] },
        { id: "7_11", question: "Thiết bị theo dõi nồng độ khí phải đưa ra cảnh báo có thể nghe và ____________", answer: "nhìn thấy", acceptedAnswers: ["nhìn thấy", "quan sát được"] },
        { id: "7_12", question: "Không gian kín chứa khí độc phải được thông gió ____________ trước khi kiểm tra và đi vào.", answer: "24 tiếng", acceptedAnswers: ["24 tiếng", "24 giờ", "24h"] },
        { id: "7_13", question: "Các đường ống dẫn khí độc hại xâm nhập vào không gian kín phải được che bằng ____________", answer: "miếng pích", acceptedAnswers: ["miếng pích", "bích mù", "mặt bích"] },
        { id: "7_14", question: "Nồng độ khí cháy nổ trong không gian kín phải được duy trì ở mức ____________", answer: "0% LEL", acceptedAnswers: ["0% LEL", "0%"] },
        { id: "7_15", question: "Việc đưa một tay vào trong không gian kín để ____________ thì không được xem là đi vào không gian kín.", answer: "kiểm tra khí", acceptedAnswers: ["kiểm tra khí", "đo khí"] },
        { id: "7_16", question: "Người vào làm việc phải lập tức ____________ khu vực khi người cảnh giới yêu cầu.", answer: "rời khỏi", acceptedAnswers: ["rời khỏi", "di tản khỏi"] },
        { id: "7_17", question: "Người cảnh giới phải canh gác ở ngoài không gian kín cho đến khi có người được phân quyền ____________", answer: "đến thay thế", acceptedAnswers: ["đến thay thế", "thay thế"] },
        { id: "7_18", question: "Các phương thức liên lạc giữa người bên trong và cảnh giới bao gồm giọng nói, bộ đàm, dây cứu sinh, và ____________", answer: "tín hiệu", acceptedAnswers: ["tín hiệu"] },
        { id: "7_19", question: "Tuyệt đối không ai được vào cứu hộ nếu không có sự hỗ trợ của ____________ khẩn cấp.", answer: "Đội ứng cứu", acceptedAnswers: ["Đội ứng cứu", "đội cứu hộ"] },
        { id: "7_20", question: "Sau mỗi tình huống khẩn cấp, giấy phép làm việc cũ sẽ bị hủy và cần phải ____________ trước khi vào làm việc lại.", answer: "gia hạn lại", acceptedAnswers: ["gia hạn lại", "xin cấp lại"] }
    ],

    // ================== ĐỀ SỐ 8 ==================
    [
        { id: "8_1", question: "Nghiêm cấm tuyệt đối sử dụng ma túy, rượu bia và ____________ trước và trong khi vận hành máy nâng.", answer: "chất kích thích", acceptedAnswers: ["chất kích thích"] },
        { id: "8_2", question: "Người vận hành cẩu nghiêm cấm sử dụng điện thoại khi đang ____________", answer: "cẩu hàng", acceptedAnswers: ["cẩu hàng", "vận hành"] },
        { id: "8_3", question: "Tuyệt đối không dùng xe cẩu để kéo máy khác hoặc để cẩu ____________", answer: "con người", acceptedAnswers: ["con người", "người"] },
        { id: "8_4", question: "Người thợ vận hành phải đọc và tham khảo bảng đặc tính ____________ trước khi làm việc.", answer: "tải trọng", acceptedAnswers: ["tải trọng"] },
        { id: "8_5", question: "Kế hoạch nâng phải được thành lập và thông báo tới toàn đội để lập ____________", answer: "biện pháp thi công", acceptedAnswers: ["biện pháp thi công"] },
        { id: "8_6", question: "Bảng kiểm tra an toàn thiết bị hàng ngày của thợ vận hành phải được kiểm soát bởi ____________", answer: "nhân viên an toàn", acceptedAnswers: ["nhân viên an toàn", "cán bộ an toàn"] },
        { id: "8_7", question: "Khoảng cách an toàn từ thiết bị nâng đến đường dây tải điện 1-20KV là ____________", answer: "2 mét", acceptedAnswers: ["2 mét", "2m", "2"] },
        { id: "8_8", question: "Đối với đường dây tải điện đến 1KV, khoảng cách an toàn nhỏ nhất là ____________", answer: "1,5 mét", acceptedAnswers: ["1,5 mét", "1.5 mét", "1.5m", "1,5m"] },
        { id: "8_9", question: "Nếu đường dây điện lên tới 150-220KV, khoảng cách an toàn tối thiểu là ____________", answer: "5 mét", acceptedAnswers: ["5 mét", "5m", "5"] },
        { id: "8_10", question: "Không dùng cần cẩu để kéo xiên tải hoặc cẩu vật đang bị vật khác ____________", answer: "vùi lấp", acceptedAnswers: ["vùi lấp", "đè lên"] },
        { id: "8_11", question: "Người vận hành cẩu không được tự ý rời khỏi buồng lái khi cần cẩu đang treo tải ____________", answer: "lơ lửng", acceptedAnswers: ["lơ lửng"] },
        { id: "8_12", question: "Khi nhận được tín hiệu STOP từ bất cứ ai, người lái phải cho ____________ thiết bị.", answer: "dừng ngay", acceptedAnswers: ["dừng ngay", "dừng lại"] },
        { id: "8_13", question: "Khi có gió từ cấp 5 (29-38km/h) trở lên, phải đưa xe cẩu về ____________", answer: "nơi an toàn", acceptedAnswers: ["nơi an toàn", "vị trí an toàn"] },
        { id: "8_14", question: "Khi đỗ xe cẩu ở mặt bằng nghiêng, bắt buộc phải dùng ____________ bánh xe.", answer: "gỗ để chèn", acceptedAnswers: ["gỗ để chèn", "chèn"] },
        { id: "8_15", question: "Quy tắc \"333\" trong nâng hạ yêu cầu nâng tải lên 30 cm, dừng trong 3 giây và người móc cáp đứng cách ____________", answer: "3 mét", acceptedAnswers: ["3 mét", "3m", "3"] },
        { id: "8_16", question: "Khối lượng riêng của sắt thép được ước tính khoảng ____________", answer: "7.800 kg/m3", acceptedAnswers: ["7.800 kg/m3", "7800 kg/m3", "7800kg/m3"] },
        { id: "8_17", question: "Khối lượng riêng của bê tông là khoảng ____________", answer: "2.500 kg/m3", acceptedAnswers: ["2.500 kg/m3", "2500 kg/m3", "2500kg/m3"] },
        { id: "8_18", question: "Khối lượng riêng của gỗ, đất, cát vào khoảng ____________", answer: "1.500 kg/m3", acceptedAnswers: ["1.500 kg/m3", "1500 kg/m3", "1500kg/m3"] },
        { id: "8_19", question: "Người vận hành xe cẩu chỉ được phép nâng tải khi đã được người xi nhan ____________ rõ ràng.", answer: "ra tín hiệu", acceptedAnswers: ["ra tín hiệu", "báo hiệu"] },
        { id: "8_20", question: "Không được nạp nhiên liệu cho thiết bị nâng khi động cơ đang chạy hoặc ở gần ____________", answer: "ngọn lửa", acceptedAnswers: ["ngọn lửa", "nguồn nhiệt"] }
    ],

    // ================== ĐỀ SỐ 9 ==================
    [
        { id: "9_1", question: "Chỉ một người duy nhất được phép xi nhan và hướng xi nhan phải ____________ với hướng nhìn của lái cẩu.", answer: "vuông góc", acceptedAnswers: ["vuông góc"] },
        { id: "9_2", question: "Tuyệt đối không hướng dẫn để vật tải đi qua khi có ____________", answer: "người bên dưới", acceptedAnswers: ["người bên dưới", "người bên dưới tải"] },
        { id: "9_3", question: "Người xi nhan nên đeo găng tay có độ nhận biết cao như màu cam, vàng, hoặc ____________", answer: "màu trắng", acceptedAnswers: ["màu trắng", "trắng"] },
        { id: "9_4", question: "Giao tiếp giữa người xi nhan và lái cẩu có thể qua tín hiệu tay tiêu chuẩn hoặc ____________", answer: "bộ đàm", acceptedAnswers: ["bộ đàm"] },
        { id: "9_5", question: "Tín hiệu tay chỉ dùng khi khoảng cách không quá xa và ____________ cho phép khả năng hiển thị.", answer: "điều kiện khí hậu", acceptedAnswers: ["điều kiện khí hậu", "thời tiết"] },
        { id: "9_6", question: "Khu vực xe cẩu làm việc phải được phong tỏa và nghiêm cấm người ____________ đi vào.", answer: "không phận sự", acceptedAnswers: ["không phận sự"] },
        { id: "9_7", question: "Sự cố của thiết bị nâng phải được ghi chép lại vào ____________ thiết bị.", answer: "sổ nhật ký", acceptedAnswers: ["sổ nhật ký", "nhật ký"] },
        { id: "9_8", question: "Khi đang cẩu hàng trên cao, người lái cần tránh thao tác điều khiển ____________", answer: "đột ngột", acceptedAnswers: ["đột ngột"] },
        { id: "9_9", question: "Sàn thao tác của giàn giáo phải có ít nhất 3 tấm lót sàn, thông thường là ____________", answer: "5 tấm", acceptedAnswers: ["5 tấm", "5"] },
        { id: "9_10", question: "Các ống nối và kẹp giàn giáo phải được đánh dấu chứng tỏ đã ____________", answer: "được kiểm tra", acceptedAnswers: ["được kiểm tra", "kiểm tra"] },
        { id: "9_11", question: "Thanh trụ chính (Standards) của giàn giáo là những ống thẳng đứng chịu lực ____________", answer: "ép tải trọng", acceptedAnswers: ["ép tải trọng", "chịu lực"] },
        { id: "9_12", question: "Khoảng cách (Bay) là khoảng cách giữa các thanh trụ đứng tính theo phương ____________", answer: "nằm ngang", acceptedAnswers: ["nằm ngang", "ngang"] },
        { id: "9_13", question: "Ống giằng ngang (Transom) được lắp đặt ____________ với thanh gờ ngăn.", answer: "vuông góc", acceptedAnswers: ["vuông góc"] },
        { id: "9_14", question: "Nếu không có thanh giằng chéo, giàn giáo sẽ bị giảm thiểu tính ____________", answer: "ổn định vững chắc", acceptedAnswers: ["ổn định vững chắc", "ổn định"] },
        { id: "9_15", question: "Lan can tay vịn ở giữa phải có chiều cao ____________ tính từ mặt sàn.", answer: "0.5 mét", acceptedAnswers: ["0.5 mét", "0.5m", "0,5m", "0.5m"] },
        { id: "9_16", question: "Chân đế giàn giáo (Base Plate) bằng sắt phải có ____________", answer: "kích thước 15x15", acceptedAnswers: ["kích thước 15x15", "15x15", "15x15cm"] },
        { id: "9_17", question: "Tấm lót chân đế (Sole Boards) bằng gỗ giúp phân bố tải trọng và phải được đặt trên mặt phẳng ____________", answer: "không lồi lõm", acceptedAnswers: ["không lồi lõm", "bằng phẳng"] },
        { id: "9_18", question: "Các loại khóa giàn giáo thông dụng được nhắc tới bao gồm khóa cup và khóa ____________", answer: "kwikstage", acceptedAnswers: ["kwikstage", "Kwikstage"] },
        { id: "9_19", question: "Lối đi trực tiếp trên giàn giáo cao hơn 5m phải có một ____________", answer: "sàn thao tác nghỉ", acceptedAnswers: ["sàn thao tác nghỉ", "chiếu nghỉ"] },
        { id: "9_20", question: "Giàn giáo sử dụng cho công tác xây dựng nặng (Heavy Construction) phải chịu được tải trọng ____________", answer: "khoảng 250 kg/m2", acceptedAnswers: ["khoảng 250 kg/m2", "250 kg/m2", "250kg/m2"] }
    ],

    // ================== ĐỀ SỐ 10 ==================
    [
        { id: "10_1", question: "Giàn giáo sử dụng cho mục đích kiểm tra, sơn hoặc lối đi (Rất nhẹ) có sức tải ____________", answer: "mức 75 kg/m2", acceptedAnswers: ["mức 75 kg/m2", "75 kg/m2", "75kg/m2"] },
        { id: "10_2", question: "Giàn giáo phải được thiết kế để chịu tải trọng gấp ____________ tải trọng tối đa theo dự kiến.", answer: "4 lần", acceptedAnswers: ["4 lần", "4"] },
        { id: "10_3", question: "Không được trộn lẫn các ống giàn giáo khác chủng loại trừ khi chúng ____________ thông số kỹ thuật.", answer: "tương xứng", acceptedAnswers: ["tương xứng", "phù hợp"] },
        { id: "10_4", question: "Chỉ sử dụng ống giàn giáo xi mạ kẽm; không sử dụng ống bị cào xước hoặc đã bị ____________", answer: "sơn phết", acceptedAnswers: ["sơn phết", "sơn"] },
        { id: "10_5", question: "Cấu trúc nền móng của giàn giáo phải bắt đầu bằng hình khối ba chiều và ____________", answer: "nền phẳng", acceptedAnswers: ["nền phẳng", "mặt phẳng"] },
        { id: "10_6", question: "Việc chuẩn bị mặt bằng tốt sẽ giúp tiết kiệm thời gian và đảm bảo ____________ cho giàn giáo.", answer: "hiệu quả ổn định", acceptedAnswers: ["hiệu quả ổn định", "sự ổn định"] },
        { id: "10_7", question: "Tấm lót sàn của giàn giáo không được để lại các ____________ giữa các ván sàn hoặc ván chân.", answer: "khoảng trống", acceptedAnswers: ["khoảng trống", "khe hở"] },
        { id: "10_8", question: "Ván chân sàn (Toe board) không yêu cầu lắp đặt ở phía trong nếu giàn giáo cách vách tường dưới ____________", answer: "25 cm", acceptedAnswers: ["25 cm", "25cm"] },
        { id: "10_9", question: "Nếu không thể khóa nối giàn giáo một cách ổn định, phải gia cố mở rộng thêm phần ____________", answer: "chân đế", acceptedAnswers: ["chân đế"] },
        { id: "10_10", question: "Các cầu thang bộ trên giàn giáo (Stair Tower) phải được lắp đặt dựa trên ____________ hợp lý.", answer: "vị trí cơ sở", acceptedAnswers: ["vị trí cơ sở"] },
        { id: "10_11", question: "Nếu đường di chuyển ngang trên giàn giáo dài hơn 15m, phải bố trí một lối thoát hiểm cứ mỗi ____________", answer: "30 mét", acceptedAnswers: ["30 mét", "30m", "30"] },
        { id: "10_12", question: "Rỉ sét ăn mòn bên trong vòng D của dây đai an toàn thường khó phát hiện vì bị ____________", answer: "dây bẹ bao phủ", acceptedAnswers: ["dây bẹ bao phủ", "dây bao phủ"] },
        { id: "10_13", question: "Các thợ hàn cần chú ý vảy hàn bắn vào dây an toàn vì chúng sẽ làm ____________ thiết bị.", answer: "hư hỏng", acceptedAnswers: ["hư hỏng", "hỏng"] },
        { id: "10_14", question: "Sự bào mòn, đứt chỉ hoặc gỉ sét ở khóa thắt lưng của dây an toàn cần được ____________ kiểm tra.", answer: "thường xuyên", acceptedAnswers: ["thường xuyên"] },
        { id: "10_15", question: "Trong không gian hạn chế, các thiết bị dẫn tĩnh điện như ống phun sơn phải được ____________", answer: "nối đất", acceptedAnswers: ["nối đất", "tiếp địa"] },
        { id: "10_16", question: "Khi làm việc với thiết bị cầm tay, không bao giờ được sử dụng các ____________", answer: "dụng cụ tự chế", acceptedAnswers: ["dụng cụ tự chế"] },
        { id: "10_17", question: "Sau khi hoàn thành đào tạo, thẻ ra vào công trường bắt buộc phải ghi rõ chức danh, mã số, công ty và ____________", answer: "hiệu lực", acceptedAnswers: ["hiệu lực", "thời hạn"] },
        { id: "10_18", question: "Khóa đào tạo này nhằm cung cấp kiến thức để công nhân tự bảo vệ bản thân và tuân thủ ____________ của Chủ đầu tư.", answer: "quy định an toàn", acceptedAnswers: ["quy định an toàn"] },
        { id: "10_19", question: "Chính sách an toàn tuyên bố giảm thiểu tác động môi trường và tối ưu hóa việc sử dụng ____________", answer: "tài nguyên", acceptedAnswers: ["tài nguyên"] },
        { id: "10_20", question: "Người lao động được phép dừng bất kỳ công việc nào có thể gây tổn hại đến con người, môi trường hoặc ____________", answer: "tài sản", acceptedAnswers: ["tài sản"] }
    ]
];