const questionBanks = [
    // ================== ĐỀ SỐ 1 ==================
    [
        { id: "1_1", question: "Mục tiêu an toàn của dự án là không thương tích, không tai nạn và không gây ________ môi trường.", answer: "ô nhiễm", acceptedAnswers: ["ô nhiễm"] },
        { id: "1_2", question: "Tất cả nhân viên có trách nhiệm và được quyền dừng bất kỳ công việc nào nếu nhận thấy công việc đó không _______", answer: "an toàn", acceptedAnswers: ["an toàn"] },
        { id: "1_3", question: "Việc tập trung và tập thể dục buổi sáng được tiến hành vào lúc _______", answer: "buổi sáng", acceptedAnswers: ["buổi sáng"] },
        { id: "1_4", question: "Khẩu hiệu an toàn của công trường là \"An toàn là trên hết, _______________ , về nhà vui vẻ\".", answer: "làm an toàn", acceptedAnswers: ["làm an toàn"] },
        { id: "1_5", question: "Nếu không có _______________ , công nhân tuyệt đối không được làm việc.", answer: "giấy phép", acceptedAnswers: ["giấy phép"] },
        { id: "1_6", question: "Thời hạn của giấy phép làm việc là ________, và được ký hàng ngày.", answer: "bảy ngày", acceptedAnswers: ["bảy ngày"] },
        { id: "1_7", question: "Buổi họp nhóm thảo luận phân tích mối nguy và nhiệm vụ an toàn được gọi là _________", answer: "họp nhóm", acceptedAnswers: ["họp nhóm"] },
        { id: "1_8", question: "Bất kỳ nhân viên nào bị phát hiện sử dụng rượu bia sẽ bị trục xuất khỏi công trường ___________", answer: "vĩnh viễn", acceptedAnswers: ["vĩnh viễn"] },
        { id: "1_9", question: "Hành vi trộm cắp, đánh nhau sẽ bị phạt, trục xuất và báo _______", answer: "công an", acceptedAnswers: ["công an"] },
        { id: "1_10", question: "Thẻ ra vào công trường sẽ được phát sau khi bạn hoàn thành _________", answer: "đào tạo", acceptedAnswers: ["đào tạo"] },
        { id: "1_11", question: "Mọi người phải đảm bảo có _________ trước khi làm việc.", answer: "sức khỏe", acceptedAnswers: ["sức khỏe"] },
        { id: "1_12", question: "Buổi họp nhóm S.T.A.R.T được tiến hành ngay tại _______", answer: "nơi làm", acceptedAnswers: ["nơi làm"] },
        { id: "1_13", question: "Trong buổi họp đầu giờ, giám sát và công nhân sẽ trao đổi 2 chiều về các ________", answer: "mối nguy", acceptedAnswers: ["mối nguy"] },
        { id: "1_14", question: "Mỗi nhóm làm việc tại công trường được chia tối đa _________", answer: "hai mươi", acceptedAnswers: ["hai mươi"] },
        { id: "1_15", question: "Nghiêm cấm hút thuốc, dùng chất kích thích, uống rượu bia và _______ trong công trường.", answer: "đánh bạc", acceptedAnswers: ["đánh bạc"] },
        { id: "1_16", question: "Trước khi tiến hành thực hiện công việc, công nhân phải ký vào ________", answer: "thẻ họp", acceptedAnswers: ["thẻ họp"] },
        { id: "1_17", question: "Chính sách dự án yêu cầu báo cáo và kịp thời điều tra sự cố để xác định nguyên nhân và có _________ thích hợp.", answer: "biện pháp", acceptedAnswers: ["biện pháp"] },
        { id: "1_18", question: "Dự án cung cấp các chương trình đào tạo về Sức khỏe, An toàn, Môi trường và _________", answer: "giám sát", acceptedAnswers: ["giám sát"] },
        { id: "1_19", question: "Người lao động phải đảm bảo luôn mang theo _______ tại mọi thời điểm.", answer: "thẻ đeo", acceptedAnswers: ["thẻ đeo"] },
        { id: "1_20", question: "Người lao động bắt buộc phải tham dự thảo luận và nói chuyện _________", answer: "an toàn", acceptedAnswers: ["an toàn"] }
    ],

    // ================== ĐỀ SỐ 2 ==================
    [
        { id: "2_1", question: "Trang thiết bị bảo vệ cá nhân (PPE) bắt buộc khi vào công trường gồm: nón, kính, quần áo và ___________", answer: "giày bảo hộ", acceptedAnswers: ["giày bảo hộ"] },
        { id: "2_2", question: "Ngoài trang bị tối thiểu, công việc hàn cắt yêu cầu thêm ___________ , găng tay hàn.", answer: "mặt nạ hàn", acceptedAnswers: ["mặt nạ hàn"] },
        { id: "2_3", question: "Dọn dẹp vệ sinh sạch sẽ đồng nghĩa với _________ cao.", answer: "năng suất", acceptedAnswers: ["năng suất"] },
        { id: "2_4", question: "Toàn bộ công nhân tiến hành vệ sinh khu vực làm việc _________ khi kết thúc ngày làm việc.", answer: "trước tiên", acceptedAnswers: ["trước tiên"] },
        { id: "2_5", question: "Việc giữ lối đi lại sạch sẽ giúp thoát người nhanh nhất trong _________", answer: "khẩn cấp", acceptedAnswers: ["khẩn cấp"] },
        { id: "2_6", question: "Nếu vệ sinh công nghiệp kém, các tai nạn chủ yếu xảy ra là _________", answer: "trượt ngã", acceptedAnswers: ["trượt ngã"] },
        { id: "2_7", question: "Đầu mẩu que hàn, xỉ hàn được phân loại vào nhóm _________", answer: "rác nguy hại", acceptedAnswers: ["rác nguy hại"] },
        { id: "2_8", question: "Rác sinh hoạt bao gồm thức ăn thừa, vỏ hộp, túi nilon và ________", answer: "giấy ăn", acceptedAnswers: ["giấy ăn"] },
        { id: "2_9", question: "Mọi người phải tuyệt đối tuân thủ mọi _____________ và hàng rào.", answer: "biển cảnh báo", acceptedAnswers: ["biển cảnh báo"] },
        { id: "2_10", question: "Hệ thống mã màu được phân chia theo 4 mùa: Đông, Xuân, Hạ và _______", answer: "mùa thu", acceptedAnswers: ["mùa thu"] },
        { id: "2_11", question: "Chai khí oxy, argon, CO2 không được để tự do mà phải được _________ bằng dây xích.", answer: "chằng buộc", acceptedAnswers: ["chằng buộc"] },
        { id: "2_12", question: "Khi không sử dụng, các chai khí phải luôn ________", answer: "đậy nắp", acceptedAnswers: ["đậy nắp"] },
        { id: "2_13", question: "Khi vận chuyển chai khí phải dùng xe chuyên dụng, tuyệt đối không dùng xe bò hoặc _______", answer: "bê tay", acceptedAnswers: ["bê tay"] },
        { id: "2_14", question: "Bất kỳ dụng cụ cầm tay nào giúp công việc dễ dàng hơn đều phải sử dụng _________", answer: "đúng cách", acceptedAnswers: ["đúng cách"] },
        { id: "2_15", question: "Đôi bàn tay và các ngón tay của con người là bộ phận ________", answer: "vô giá", acceptedAnswers: ["vô giá"] },
        { id: "2_16", question: "Thiết bị điện cầm tay phải được Ban Quản lý Dự án _________ khi sử dụng.", answer: "kiểm tra", acceptedAnswers: ["kiểm tra"] },
        { id: "2_17", question: "Khi sửa chữa hoặc thay thế thiết bị điện cầm tay, bắt buộc phải _________", answer: "rút phích", acceptedAnswers: ["rút phích"] },
        { id: "2_18", question: "Thiết bị cầm tay phải đầy đủ nắp bảo vệ và ___________ nếu có.", answer: "tay cầm phụ", acceptedAnswers: ["tay cầm phụ"] },
        { id: "2_19", question: "Gỗ thải và kim loại vụn phải được _________ rõ ràng tại khu vực tập kết.", answer: "phân loại", acceptedAnswers: ["phân loại"] },
        { id: "2_20", question: "Người lao động phải sử dụng ________ cho mọi công việc để ngăn chặn chấn thương.", answer: "găng tay", acceptedAnswers: ["găng tay"] }
    ],

    // ================== ĐỀ SỐ 3 ==================
    [
        { id: "3_1", question: "Khi nâng vật nặng, mức độ tác động lên cột sống sẽ giảm khi vật nâng được đặt _________", answer: "gần người", acceptedAnswers: ["gần người"] },
        { id: "3_2", question: "Nếu vật quá nặng, công nhân cần sử dụng ___________ hoặc gọi thêm người.", answer: "xe nâng hàng", acceptedAnswers: ["xe nâng hàng"] },
        { id: "3_3", question: "Khi tự nâng vật nặng, công nhân phải hạ thấp cơ thể và giữ cho __________", answer: "lưng thẳng", acceptedAnswers: ["lưng thẳng"] },
        { id: "3_4", question: "Công việc có phát sinh nguồn nhiệt hoặc tia lửa được gọi là ____________", answer: "việc sinh nhiệt", acceptedAnswers: ["việc sinh nhiệt"] },
        { id: "3_5", question: "Tại nơi làm việc phát sinh nhiệt, luôn phải trang bị _____________", answer: "bình chữa cháy", acceptedAnswers: ["bình chữa cháy"] },
        { id: "3_6", question: "Khoảng cách tối thiểu giữa nguồn sinh nhiệt và vật liệu bắt lửa là _______", answer: "sáu mét", acceptedAnswers: ["sáu mét"] },
        { id: "3_7", question: "Ba yếu tố tạo nên sự cháy bao gồm: Nhiên liệu, Nguồn nhiệt và _______", answer: "khí oxy", acceptedAnswers: ["khí oxy"] },
        { id: "3_8", question: "Công nhân tham gia hoạt động nâng hạ, cẩu kéo bắt buộc phải _________", answer: "đào tạo", acceptedAnswers: ["đào tạo"] },
        { id: "3_9", question: "Trong quá trình cẩu hàng, người lao động phải sử dụng _______ để điều khiển vật nâng.", answer: "dây lèo", acceptedAnswers: ["dây lèo"] },
        { id: "3_10", question: "Trước khi cẩu, phải thiết lập an toàn bằng cách kiểm tra ________", answer: "nền đất", acceptedAnswers: ["nền đất"] },
        { id: "3_11", question: "Tấm kê chân của xe cẩu phải được đặt trên nền đất _________", answer: "vững chắc", acceptedAnswers: ["vững chắc"] },
        { id: "3_12", question: "Trong quá trình cẩu, tuyệt đối không được đứng _________", answer: "dưới tải", acceptedAnswers: ["dưới tải"] },
        { id: "3_13", question: "Nơi nghỉ ngơi, giải lao không được nằm trong góc khuất, không nhìn thấy của lái cẩu và ________", answer: "lái máy", acceptedAnswers: ["lái máy"] },
        { id: "3_14", question: "Nghiêm cấm công nhân ngủ trong cabin, buồng lái và nghỉ ngơi ngay tại _______", answer: "tủ điện", acceptedAnswers: ["tủ điện"] },
        { id: "3_15", question: "Hóa chất và xúc tác yêu cầu người dùng phải đọc __________ trước khi sử dụng.", answer: "bảng chỉ dẫn", acceptedAnswers: ["bảng chỉ dẫn"] },
        { id: "3_16", question: "Sau khi sử dụng hóa chất và xúc tác, khu vực làm việc phải được _________", answer: "vệ sinh", acceptedAnswers: ["vệ sinh"] },
        { id: "3_17", question: "Khi có báo động khẩn cấp, người lao động phải dừng việc, di tản bằng cách đi bộ nhanh ra __________", answer: "cổng chính", acceptedAnswers: ["cổng chính"] },
        { id: "3_18", question: "Tại điểm tập trung, nhân viên không được rời đi cho đến khi đếm số lượng nhân viên _________", answer: "hoàn tất", acceptedAnswers: ["hoàn tất"] },
        { id: "3_19", question: "Người ra tín hiệu (người xi nhan) phải đứng ở vị trí đảm bảo người lái cẩu _________", answer: "nhìn thấy", acceptedAnswers: ["nhìn thấy"] },
        { id: "3_20", question: "Khi điều khiển bằng tay, hướng xi nhan phải vuông góc với _________ của lái cẩu.", answer: "tầm nhìn", acceptedAnswers: ["tầm nhìn"] }
    ],

    // ================== ĐỀ SỐ 4 ==================
    [
        { id: "4_1", question: "Làm việc ở độ cao đã được chứng minh là một trong những hoạt động ___________ trong xây dựng.", answer: "nguy hiểm nhất", acceptedAnswers: ["nguy hiểm nhất"] },
        { id: "4_2", question: "Theo thống kê, hai phần ba số trường hợp tử vong trong xây dựng có liên quan tới việc _______", answer: "rơi ngã", acceptedAnswers: ["rơi ngã"] },
        { id: "4_3", question: "Hệ thống chống té ngã chủ yếu bao gồm tay vịn, thành lan can, tấm chắn chân và ___________ tiêu chuẩn.", answer: "sàn thao tác", acceptedAnswers: ["sàn thao tác"] },
        { id: "4_4", question: "Lan can bảo vệ trên cao phải đạt khoảng cách từ ___________", answer: "một mét rưỡi", acceptedAnswers: ["một mét rưỡi"] },
        { id: "4_5", question: "Tấm chặn chân trên giàn giáo phải có chiều cao ít nhất là ________", answer: "mười phân", acceptedAnswers: ["mười phân"] },
        { id: "4_6", question: "Người lao động phải mang dây an toàn toàn thân khi làm việc với độ cao từ _______ hoặc lớn hơn.", answer: "hai mét", acceptedAnswers: ["hai mét"] },
        { id: "4_7", question: "Khi làm việc trên cao, 100% công nhân phải buộc chặt dây móc an toàn ở vị trí _________", answer: "vững chắc", acceptedAnswers: ["vững chắc"] },
        { id: "4_8", question: "Chỗ móc dây an toàn phải có khả năng chịu được tải trọng ________ tương đương 2.3 tấn.", answer: "hai tấn", acceptedAnswers: ["hai tấn"] },
        { id: "4_9", question: "Không được sử dụng đường ống có vít, ống dẫn, hoặc tay vịn bằng gỗ làm _________", answer: "điểm móc", acceptedAnswers: ["điểm móc"] },
        { id: "4_10", question: "Dây cáp của móc dây an toàn phải có độ dày xấp xỉ ________", answer: "một phân", acceptedAnswers: ["một phân"] },
        { id: "4_11", question: "Không dùng dây thừng bện từ ___________ để làm dây cứu sinh.", answer: "sợi tự nhiên", acceptedAnswers: ["sợi tự nhiên"] },
        { id: "4_12", question: "Việc lắp đặt dây cứu sinh chỉ được thực hiện bởi ________", answer: "chuyên gia", acceptedAnswers: ["chuyên gia"] },
        { id: "4_13", question: "Người dùng phải kiểm tra dây thắt an toàn ________ sử dụng.", answer: "trước khi", acceptedAnswers: ["trước khi"] },
        { id: "4_14", question: "Các tia cực tím (UV) có thể làm giảm độ bền của dây bẹ an toàn tới ________", answer: "một phần ba", acceptedAnswers: ["một phần ba"] },
        { id: "4_15", question: "Không để dây an toàn tiếp xúc với nhiệt độ lớn hơn ________", answer: "tám mươi độ", acceptedAnswers: ["tám mươi độ"] },
        { id: "4_16", question: "Một vết cắt nhỏ 1 mm có thể làm mất từ 5% đến 39% ________ của dây an toàn.", answer: "sức bền", acceptedAnswers: ["sức bền"] },
        { id: "4_17", question: "Khi thắt dây an toàn, phải đặt tâm của khóa chữ D nối giữa hai ___________", answer: "dây đai vai", acceptedAnswers: ["dây đai vai"] },
        { id: "4_18", question: "Dây đai ngực phải cho phép khoảng cách mở rộng ngực bằng ___________", answer: "một nắm tay", acceptedAnswers: ["một nắm tay"] },
        { id: "4_19", question: "Tất cả các thiết bị chống rơi phải được kiểm tra và đánh mã màu cứ ________ một lần.", answer: "ba tháng", acceptedAnswers: ["ba tháng"] },
        { id: "4_20", question: "Người lao động không được ném vật liệu, ________ từ trên cao xuống.", answer: "dụng cụ", acceptedAnswers: ["dụng cụ"] }
    ],

    // ================== ĐỀ SỐ 5 ==================
    [
        { id: "5_1", question: "Người có trách nhiệm về giàn giáo mới được phép ________ giàn giáo hoặc thay đổi cấu trúc.", answer: "treo thẻ", acceptedAnswers: ["treo thẻ"] },
        { id: "5_2", question: "Thang sử dụng phải nới rộng cao hơn khu vực làm việc và tuân theo _________ để đảm bảo độ dốc.", answer: "quy chuẩn", acceptedAnswers: ["quy chuẩn"] },
        { id: "5_3", question: "Khi trèo thang, công nhân phải đảm bảo tiếp xúc ________ an toàn.", answer: "ba điểm", acceptedAnswers: ["ba điểm"] },
        { id: "5_4", question: "Không sử dụng thang trên bề mặt trơn trượt, trừ khi có ____________ đi kèm.", answer: "đế chống trượt", acceptedAnswers: ["đế chống trượt"] },
        { id: "5_5", question: "Tuyệt đối không đặt thang trên bề mặt _______ hoặc không ổn định.", answer: "lồi lõm", acceptedAnswers: ["lồi lõm"] },
        { id: "5_6", question: "Nếu thang đặt gần các thiết bị điện, thang phải được làm bằng chất liệu cách điện như gỗ hoặc _____________", answer: "sợi thủy tinh", acceptedAnswers: ["sợi thủy tinh"] },
        { id: "5_7", question: "Tuyệt đối không sử dụng điểm trên cùng hoặc ___________ của thang.", answer: "bậc cao nhất", acceptedAnswers: ["bậc cao nhất"] },
        { id: "5_8", question: "Các tay vịn 2 bên của thang di động phải cách nhau ít nhất ________", answer: "ba mươi phân", acceptedAnswers: ["ba mươi phân"] },
        { id: "5_9", question: "Nếu thang bị hỏng, phải đánh dấu ngay lập tức hoặc treo thẻ ____________", answer: "cấm sử dụng", acceptedAnswers: ["cấm sử dụng"] },
        { id: "5_10", question: "Khi trèo lên hoặc xuống thang, mặt phải luôn _________ thang.", answer: "hướng vào", acceptedAnswers: ["hướng vào"] },
        { id: "5_11", question: "Không mang đồ dùng hoặc tải trọng trên tay khi trèo thang vì có thể làm bạn ____________", answer: "mất cân bằng", acceptedAnswers: ["mất cân bằng"] },
        { id: "5_12", question: "Khi sử dụng thang để thao tác trên mặt sàn, thang phải cao hơn mặt sàn ít nhất ________ trở lên.", answer: "một mét", acceptedAnswers: ["một mét"] },
        { id: "5_13", question: "Các thanh thang phải được bố trí cách nhau vừa đủ theo _________", answer: "quy định", acceptedAnswers: ["quy định"] },
        { id: "5_14", question: "Công nhân tuyệt đối không được đi 2 người trên _________", answer: "một thang", acceptedAnswers: ["một thang"] },
        { id: "5_15", question: "Ván sàn của giàn giáo phải được _________ để hỗ trợ làm việc.", answer: "cố định", acceptedAnswers: ["cố định"] },
        { id: "5_16", question: "Khi làm việc tại các khu vực cheo leo nguy hiểm, công nhân phải được trang bị ____________", answer: "dây cứu sinh", acceptedAnswers: ["dây cứu sinh"] },
        { id: "5_17", question: "Giàn giáo là nguyên nhân gây ra hàng ngàn tai nạn và hàng trăm ca ________ mỗi năm.", answer: "tử vong", acceptedAnswers: ["tử vong"] },
        { id: "5_18", question: "Các tấm lót sàn giàn giáo bằng gỗ có kích thước chuẩn yêu cầu rộng ________", answer: "hai mươi phân", acceptedAnswers: ["hai mươi phân"] },
        { id: "5_19", question: "Các tấm ván lót sàn phải được đánh dấu bằng sơn ở _______ , không sơn toàn bộ.", answer: "hai đầu", acceptedAnswers: ["hai đầu"] },
        { id: "5_20", question: "Khoảng cách an toàn để khóa nối giàn giáo là cứ mỗi ________ theo chiều cao.", answer: "bốn mét", acceptedAnswers: ["bốn mét"] }
    ],

    // ================== ĐỀ SỐ 6 ==================
    [
        { id: "6_1", question: "Không gian hạn chế là nơi đủ rộng để đi vào làm việc nhưng bị hạn chế __________ và không thiết kế làm việc lâu dài.", answer: "lối ra vào", acceptedAnswers: ["lối ra vào"] },
        { id: "6_2", question: "Các mối nguy hiểm vật lý trong không gian hạn chế bao gồm tiếng ồn, nhiệt độ, điện, và ________", answer: "tầm nhìn", acceptedAnswers: ["tầm nhìn"] },
        { id: "6_3", question: "Không khí thông thường chứa tỉ lệ oxy ở mức _________", answer: "tiêu chuẩn", acceptedAnswers: ["tiêu chuẩn"] },
        { id: "6_4", question: "Không khí bị coi là thiếu oxy khi nồng độ oxy giảm tới mức ________", answer: "nguy hiểm", acceptedAnswers: ["nguy hiểm"] },
        { id: "6_5", question: "Khi nồng độ oxy giảm thấp, con người bắt đầu có triệu chứng giảm _________", answer: "phối hợp", acceptedAnswers: ["phối hợp"] },
        { id: "6_6", question: "Môi trường có nồng độ oxy cao quá mức được gọi là ________", answer: "dư oxy", acceptedAnswers: ["dư oxy"] },
        { id: "6_7", question: "Không được tồn trữ bồn hoặc ____________ trong không gian kín.", answer: "bình khí nén", acceptedAnswers: ["bình khí nén"] },
        { id: "6_8", question: "Khí Hydro Sunphua (H2S) là khí không màu, nặng hơn không khí và có mùi _________", answer: "trứng thối", acceptedAnswers: ["trứng thối"] },
        { id: "6_9", question: "Khí H2S có thể làm mất khả năng khứu giác của con người ở mức nồng độ ________", answer: "cao đậm", acceptedAnswers: ["cao đậm"] },
        { id: "6_10", question: "Cacbon Monoxit (CO) là sản phẩm phụ của quá trình đốt cháy, nhẹ hơn không khí và hoàn toàn _________", answer: "không mùi", acceptedAnswers: ["không mùi"] },
        { id: "6_11", question: "Hóa chất độc hại trong không gian kín có thể đi vào cơ thể qua hô hấp, nuốt, hoặc ________", answer: "thấm da", acceptedAnswers: ["thấm da"] },
        { id: "6_12", question: "Các loại khí dễ cháy thường gặp trong không gian kín bao gồm CH4, C2H2, nhiên liệu, dung môi và ________", answer: "bụi than", acceptedAnswers: ["bụi than"] },
        { id: "6_13", question: "Sự khuếch đại âm thanh trong không gian kín tạo ra mối nguy về ________ làm tác động khả năng giao tiếp.", answer: "tiếng ồn", acceptedAnswers: ["tiếng ồn"] },
        { id: "6_14", question: "Làm sạch không gian kín bằng ______ là một nguyên nhân gây thiếu oxy.", answer: "khí trơ", acceptedAnswers: ["khí trơ"] },
        { id: "6_15", question: "Hóa chất kích ứng có thể làm người lao động chóng mặt, buồn nôn hoặc _______", answer: "khó thở", acceptedAnswers: ["khó thở"] },
        { id: "6_16", question: "Không sử dụng _______ để thông gió trong không gian hạn chế.", answer: "khí oxy", acceptedAnswers: ["khí oxy"] },
        { id: "6_17", question: "Khí CO có giới hạn tiếp xúc an toàn được quy định theo ________", answer: "tiêu chuẩn", acceptedAnswers: ["tiêu chuẩn"] },
        { id: "6_18", question: "Mối nguy ngập lụt, sụt, lún hoặc ________ thường hiện diện trong không gian kín.", answer: "sạt lở", acceptedAnswers: ["sạt lở"] },
        { id: "6_19", question: "Các thiết bị bảo hộ lao động bổ sung có thể làm tăng nhiệt độ cơ thể do ________ nặng nề.", answer: "sức nặng", acceptedAnswers: ["sức nặng"] },
        { id: "6_20", question: "Người lao động làm việc trong không gian kín cần được _________ thường xuyên hơn.", answer: "nghỉ ngơi", acceptedAnswers: ["nghỉ ngơi"] }
    ],

    // ================== ĐỀ SỐ 7 ==================
    [
        { id: "7_1", question: "Khi dừng công việc, phải bố trí _____________ để cấm người không phận sự vào không gian kín.", answer: "rào chắn cứng", acceptedAnswers: ["rào chắn cứng", "rào chắn"] },
        { id: "7_2", question: "Biển cảnh báo phải được đặt ở tất cả các _________ của không gian kín.", answer: "lối ra vào", acceptedAnswers: ["lối ra vào", "cửa ra vào"] },
        { id: "7_3", question: "Trước khi vào làm việc, người lao động phải được cấp phép, khỏe mạnh về thể chất và _________", answer: "tinh thần", acceptedAnswers: ["tinh thần"] },
        { id: "7_4", question: "Chỉ sử dụng thiết bị điện có ____________ để thắp sáng trong không gian kín.", answer: "điện áp thấp", acceptedAnswers: ["điện áp thấp"] },
        { id: "7_5", question: "Giấy phép làm việc trong không gian hạn chế phải được yêu cầu trước ___________", answer: "hai mươi tư", acceptedAnswers: ["hai mươi tư", "một ngày"] },
        { id: "7_6", question: "Bản giấy phép làm việc bắt buộc phải được đặt tại ________ không gian kín.", answer: "lối vào", acceptedAnswers: ["lối vào", "cửa vào"] },
        { id: "7_7", question: "Không gian kín phải được kiểm tra khí _________ trước khi vào làm việc.", answer: "một tiếng", acceptedAnswers: ["một tiếng", "một giờ"] },
        { id: "7_8", question: "Nếu công việc bị tạm dừng vì bất kỳ lý do gì, cần phải ____________ khí trước khi tiếp tục.", answer: "kiểm tra lại", acceptedAnswers: ["kiểm tra lại", "đo lại"] },
        { id: "7_9", question: "Người được Quyền Đo Khí (AGT) phải đo khí ở mọi khu vực trong không gian kín từ ________", answer: "bên ngoài", acceptedAnswers: ["bên ngoài"] },
        { id: "7_10", question: "Các thiết bị điện phải kết nối qua thiết bị chống dòng rò được đặt ở ________ không gian kín.", answer: "bên ngoài", acceptedAnswers: ["bên ngoài"] },
        { id: "7_11", question: "Thiết bị theo dõi nồng độ khí phải đưa ra cảnh báo có thể nghe và _________", answer: "nhìn thấy", acceptedAnswers: ["nhìn thấy", "quan sát"] },
        { id: "7_12", question: "Không gian kín chứa khí độc phải được thông gió ____________ trước khi kiểm tra và đi vào.", answer: "hai mươi tư", acceptedAnswers: ["hai mươi tư", "một ngày"] },
        { id: "7_13", question: "Các đường ống dẫn khí độc hại xâm nhập vào không gian kín phải được che bằng _________", answer: "bích mù", acceptedAnswers: ["bích mù", "mặt bích"] },
        { id: "7_14", question: "Nồng độ khí cháy nổ trong không gian kín phải được duy trì ở mức _________", answer: "không có", acceptedAnswers: ["không có"] },
        { id: "7_15", question: "Việc đưa một tay vào trong không gian kín để ___________ thì không được xem là đi vào không gian kín.", answer: "kiểm tra khí", acceptedAnswers: ["kiểm tra khí", "đo khí"] },
        { id: "7_16", question: "Người vào làm việc phải lập tức ________ khu vực khi người cảnh giới yêu cầu.", answer: "rời khỏi", acceptedAnswers: ["rời khỏi", "di tản"] },
        { id: "7_17", question: "Người cảnh giới phải canh gác ở ngoài không gian kín cho đến khi có người được phân quyền ________", answer: "thay thế", acceptedAnswers: ["thay thế"] },
        { id: "7_18", question: "Các phương thức liên lạc giữa người bên trong và cảnh giới bao gồm giọng nói, bộ đàm, dây cứu sinh, và ________", answer: "tín hiệu", acceptedAnswers: ["tín hiệu"] },
        { id: "7_19", question: "Tuyệt đối không ai được vào cứu hộ nếu không có sự hỗ trợ của ___________ khẩn cấp.", answer: "đội cứu hộ", acceptedAnswers: ["đội cứu hộ", "đội ứng cứu"] },
        { id: "7_20", question: "Sau mỗi tình huống khẩn cấp, giấy phép làm việc cũ sẽ bị hủy và cần phải ____________ trước khi vào làm việc lại.", answer: "xin cấp lại", acceptedAnswers: ["xin cấp lại", "gia hạn lại"] }
    ],

    // ================== ĐỀ SỐ 8 ==================
    [
        { id: "8_1", question: "Nghiêm cấm tuyệt đối sử dụng ma túy, rượu bia và _______________ trước và trong khi vận hành máy nâng.", answer: "chất kích thích", acceptedAnswers: ["chất kích thích"] },
        { id: "8_2", question: "Người vận hành cẩu nghiêm cấm sử dụng điện thoại khi đang ________", answer: "cẩu hàng", acceptedAnswers: ["cẩu hàng", "vận hành"] },
        { id: "8_3", question: "Tuyệt đối không dùng xe cẩu để kéo máy khác hoặc để cẩu _________", answer: "con người", acceptedAnswers: ["con người"] },
        { id: "8_4", question: "Người thợ vận hành phải đọc và tham khảo bảng đặc tính _________ trước khi làm việc.", answer: "tải trọng", acceptedAnswers: ["tải trọng"] },
        { id: "8_5", question: "Kế hoạch nâng phải được thành lập và thông báo tới toàn đội để lập ___________", answer: "phương án thi", acceptedAnswers: ["phương án thi", "biện pháp thi"] },
        { id: "8_6", question: "Bảng kiểm tra an toàn thiết bị hàng ngày của thợ vận hành phải được kiểm soát bởi ________", answer: "an toàn viên", acceptedAnswers: ["an toàn viên", "cán bộ an"] },
        { id: "8_7", question: "Khoảng cách an toàn từ thiết bị nâng đến đường dây tải điện từ một đến hai mươi kilôvôn là ________", answer: "hai mét", acceptedAnswers: ["hai mét"] },
        { id: "8_8", question: "Đối với đường dây tải điện đến một kilôvôn, khoảng cách an toàn nhỏ nhất là ___________", answer: "một mét rưỡi", acceptedAnswers: ["một mét rưỡi"] },
        { id: "8_9", question: "Nếu đường dây điện lên tới một trăm năm mươi đến hai trăm hai mươi kilôvôn, khoảng cách an toàn tối thiểu là ________", answer: "năm mét", acceptedAnswers: ["năm mét"] },
        { id: "8_10", question: "Không dùng cần cẩu để kéo xiên tải hoặc cẩu vật đang bị vật khác _______", answer: "vùi lấp", acceptedAnswers: ["vùi lấp", "đè lên"] },
        { id: "8_11", question: "Người vận hành cẩu không được tự ý rời khỏi buồng lái khi cần cẩu đang treo tải _______", answer: "lơ lửng", acceptedAnswers: ["lơ lửng"] },
        { id: "8_12", question: "Khi nhận được tín hiệu dừng khẩn cấp từ bất cứ ai, người lái phải cho _________ thiết bị.", answer: "dừng ngay", acceptedAnswers: ["dừng ngay", "dừng lại"] },
        { id: "8_13", question: "Khi có gió từ cấp năm trở lên, phải đưa xe cẩu về ___________", answer: "nơi an toàn", acceptedAnswers: ["nơi an toàn"] },
        { id: "8_14", question: "Khi đỗ xe cẩu ở mặt bằng nghiêng, bắt buộc phải dùng _________ bánh xe.", answer: "chèn bánh", acceptedAnswers: ["chèn bánh", "gỗ chèn"] },
        { id: "8_15", question: "Quy tắc an toàn trong nâng hạ yêu cầu nâng tải lên một khoảng nhỏ, dừng lại và người móc cáp đứng cách ________", answer: "ba mét", acceptedAnswers: ["ba mét"] },
        { id: "8_16", question: "Khối lượng riêng của sắt thép thuộc nhóm vật liệu có tỉ trọng _________", answer: "rất cao", acceptedAnswers: ["rất cao", "rất nặng"] },
        { id: "8_17", question: "Khối lượng riêng của bê tông thuộc nhóm vật liệu có tỉ trọng _________", answer: "trung bình", acceptedAnswers: ["trung bình"] },
        { id: "8_18", question: "Khối lượng riêng của gỗ, đất, cát thuộc nhóm vật liệu có tỉ trọng _________", answer: "nhẹ hơn", acceptedAnswers: ["nhẹ hơn"] },
        { id: "8_19", question: "Người vận hành xe cẩu chỉ được phép nâng tải khi đã được người xi nhan ___________ rõ ràng.", answer: "ra tín hiệu", acceptedAnswers: ["ra tín hiệu", "báo hiệu"] },
        { id: "8_20", question: "Không được nạp nhiên liệu cho thiết bị nâng khi động cơ đang chạy hoặc ở gần ________", answer: "ngọn lửa", acceptedAnswers: ["ngọn lửa", "nguồn nhiệt"] }
    ],

    // ================== ĐỀ SỐ 9 ==================
    [
        { id: "9_1", question: "Chỉ một người duy nhất được phép xi nhan và hướng xi nhan phải _________ với hướng nhìn của lái cẩu.", answer: "vuông góc", acceptedAnswers: ["vuông góc"] },
        { id: "9_2", question: "Tuyệt đối không hướng dẫn để vật tải đi qua khi có ___________", answer: "người bên dưới", acceptedAnswers: ["người bên dưới"] },
        { id: "9_3", question: "Người xi nhan nên đeo găng tay có độ nhận biết cao như màu cam, vàng, hoặc _________", answer: "màu trắng", acceptedAnswers: ["màu trắng"] },
        { id: "9_4", question: "Giao tiếp giữa người xi nhan và lái cẩu có thể qua tín hiệu tay tiêu chuẩn hoặc _______", answer: "bộ đàm", acceptedAnswers: ["bộ đàm"] },
        { id: "9_5", question: "Tín hiệu tay chỉ dùng khi khoảng cách không quá xa và _________ cho phép khả năng hiển thị.", answer: "thời tiết", acceptedAnswers: ["thời tiết"] },
        { id: "9_6", question: "Khu vực xe cẩu làm việc phải được phong tỏa và nghiêm cấm người _____________ đi vào.", answer: "không phận sự", acceptedAnswers: ["không phận sự"] },
        { id: "9_7", question: "Sự cố của thiết bị nâng phải được ghi chép lại vào __________ thiết bị.", answer: "sổ nhật ký", acceptedAnswers: ["sổ nhật ký", "nhật ký"] },
        { id: "9_8", question: "Khi đang cẩu hàng trên cao, người lái cần tránh thao tác điều khiển ________", answer: "đột ngột", acceptedAnswers: ["đột ngột"] },
        { id: "9_9", question: "Sàn thao tác của giàn giáo phải có ít nhất ba tấm lót sàn, thông thường là ________", answer: "năm tấm", acceptedAnswers: ["năm tấm"] },
        { id: "9_10", question: "Các ống nối và kẹp giàn giáo phải được đánh dấu chứng tỏ đã _________", answer: "kiểm tra", acceptedAnswers: ["kiểm tra"] },
        { id: "9_11", question: "Thanh trụ chính của giàn giáo là những ống thẳng đứng _________", answer: "chịu lực", acceptedAnswers: ["chịu lực"] },
        { id: "9_12", question: "Khoảng cách giữa các thanh trụ đứng tính theo phương _________", answer: "nằm ngang", acceptedAnswers: ["nằm ngang"] },
        { id: "9_13", question: "Ống giằng ngang được lắp đặt _________ với thanh gờ ngăn.", answer: "vuông góc", acceptedAnswers: ["vuông góc"] },
        { id: "9_14", question: "Nếu không có thanh giằng chéo, giàn giáo sẽ bị giảm thiểu tính _______", answer: "ổn định", acceptedAnswers: ["ổn định"] },
        { id: "9_15", question: "Lan can tay vịn ở giữa phải có chiều cao _________ tính từ mặt sàn.", answer: "nửa mét", acceptedAnswers: ["nửa mét"] },
        { id: "9_16", question: "Chân đế giàn giáo bằng sắt phải có kích thước ________", answer: "vừa vặn", acceptedAnswers: ["vừa vặn", "tiêu chuẩn"] },
        { id: "9_17", question: "Tấm lót chân đế bằng gỗ giúp phân bố tải trọng và phải được đặt trên mặt phẳng ___________", answer: "bằng phẳng", acceptedAnswers: ["bằng phẳng"] },
        { id: "9_18", question: "Các loại khóa giàn giáo thông dụng được nhắc tới bao gồm khóa cúp và khóa _________", answer: "chuyên dụng", acceptedAnswers: ["chuyên dụng"] },
        { id: "9_19", question: "Lối đi trực tiếp trên giàn giáo cao hơn năm mét phải có một _________", answer: "chiếu nghỉ", acceptedAnswers: ["chiếu nghỉ", "sàn nghỉ"] },
        { id: "9_20", question: "Giàn giáo sử dụng cho công tác xây dựng nặng phải chịu được tải trọng _________", answer: "mức cao", acceptedAnswers: ["mức cao", "rất lớn"] }
    ],

    // ================== ĐỀ SỐ 10 ==================
    [
        { id: "10_1", question: "Giàn giáo sử dụng cho mục đích kiểm tra, sơn hoặc lối đi rất nhẹ có sức tải _________", answer: "mức nhẹ", acceptedAnswers: ["mức nhẹ", "mức thấp"] },
        { id: "10_2", question: "Giàn giáo phải được thiết kế để chịu tải trọng gấp ________ tải trọng tối đa theo dự kiến.", answer: "bốn lần", acceptedAnswers: ["bốn lần"] },
        { id: "10_3", question: "Không được trộn lẫn các ống giàn giáo khác chủng loại trừ khi chúng _________ thông số kỹ thuật.", answer: "tương xứng", acceptedAnswers: ["tương xứng", "phù hợp"] },
        { id: "10_4", question: "Chỉ sử dụng ống giàn giáo xi mạ kẽm; không sử dụng ống bị cào xước hoặc đã bị _________", answer: "sơn phết", acceptedAnswers: ["sơn phết"] },
        { id: "10_5", question: "Cấu trúc nền móng của giàn giáo phải bắt đầu bằng hình khối ba chiều và _________", answer: "nền phẳng", acceptedAnswers: ["nền phẳng", "mặt phẳng"] },
        { id: "10_6", question: "Việc chuẩn bị mặt bằng tốt sẽ giúp tiết kiệm thời gian và đảm bảo ___________ cho giàn giáo.", answer: "sự ổn định", acceptedAnswers: ["sự ổn định"] },
        { id: "10_7", question: "Tấm lót sàn của giàn giáo không được để lại các ___________ giữa các ván sàn hoặc ván chân.", answer: "khoảng trống", acceptedAnswers: ["khoảng trống", "khe hở"] },
        { id: "10_8", question: "Ván chân sàn không yêu cầu lắp đặt ở phía trong nếu giàn giáo cách vách tường một khoảng _________", answer: "rất nhỏ", acceptedAnswers: ["rất nhỏ", "rất ngắn"] },
        { id: "10_9", question: "Nếu không thể khóa nối giàn giáo một cách ổn định, phải gia cố mở rộng thêm phần _______", answer: "chân đế", acceptedAnswers: ["chân đế"] },
        { id: "10_10", question: "Các cầu thang bộ trên giàn giáo phải được lắp đặt dựa trên ___________ hợp lý.", answer: "vị trí gốc", acceptedAnswers: ["vị trí gốc", "vị trí cơ"] },
        { id: "10_11", question: "Nếu đường di chuyển ngang trên giàn giáo dài, phải bố trí lối thoát hiểm theo khoảng cách _________", answer: "quy định", acceptedAnswers: ["quy định", "tiêu chuẩn"] },
        { id: "10_12", question: "Rỉ sét ăn mòn bên trong vòng D của dây đai an toàn thường khó phát hiện vì bị ___________", answer: "dây bao phủ", acceptedAnswers: ["dây bao phủ"] },
        { id: "10_13", question: "Các thợ hàn cần chú ý vảy hàn bắn vào dây an toàn vì chúng sẽ làm _______ thiết bị.", answer: "hư hỏng", acceptedAnswers: ["hư hỏng"] },
        { id: "10_14", question: "Sự bào mòn, đứt chỉ hoặc gỉ sét ở khóa thắt lưng của dây an toàn cần được ___________ kiểm tra.", answer: "thường xuyên", acceptedAnswers: ["thường xuyên"] },
        { id: "10_15", question: "Trong không gian hạn chế, các thiết bị dẫn tĩnh điện như ống phun sơn phải được _______", answer: "nối đất", acceptedAnswers: ["nối đất", "tiếp địa"] },
        { id: "10_16", question: "Khi làm việc với thiết bị cầm tay, không bao giờ được sử dụng các ____________", answer: "đồ tự chế", acceptedAnswers: ["đồ tự chế", "dụng cụ tự"] },
        { id: "10_17", question: "Sau khi hoàn thành đào tạo, thẻ ra vào công trường bắt buộc phải ghi rõ chức danh, mã số, công ty và ________", answer: "hiệu lực", acceptedAnswers: ["hiệu lực", "thời hạn"] },
        { id: "10_18", question: "Khóa đào tạo này nhằm cung cấp kiến thức để công nhân tự bảo vệ bản thân và tuân thủ _________ của Chủ đầu tư.", answer: "nội quy an", acceptedAnswers: ["nội quy an", "quy định an"] },
        { id: "10_19", question: "Chính sách an toàn tuyên bố giảm thiểu tác động môi trường và tối ưu hóa việc sử dụng _________", answer: "tài nguyên", acceptedAnswers: ["tài nguyên"] },
        { id: "10_20", question: "Người lao động được phép dừng bất kỳ công việc nào có thể gây tổn hại đến con người, môi trường hoặc _______", answer: "tài sản", acceptedAnswers: ["tài sản"] }
    ]
];